version: '3.8'

services:

  veterinaria:
    stdin_open: true
    container_name: veterinaria
    build: ./Veterinaria
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - docker_veterinaria
    deploy:
      resources:
        limits:
          memory: 1G


networks:
  docker_veterinaria:
    driver: bridge
    name: docker_veterinaria